# Generated by Django 3.2.13 on 2022-06-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_events_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
