# Generated by Django 3.2.13 on 2022-07-02 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220702_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.college'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.department'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.program'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.year'),
        ),
    ]
