# Generated by Django 3.2.13 on 2022-07-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220702_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='detail_filled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
