# Generated by Django 3.2.13 on 2022-07-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_profile_detail_filled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
