# Generated by Django 3.2.13 on 2022-07-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_user_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3, null=True),
        ),
    ]
