# Generated by Django 3.2.13 on 2022-07-12 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_user_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffadmin',
            name='detail_filled_s',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffadmin',
            name='gender',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='staffadmin',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.club'),
        ),
        migrations.AlterField(
            model_name='staffadmin',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.college'),
        ),
        migrations.AlterField(
            model_name='staffadmin',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.department'),
        ),
        migrations.AlterField(
            model_name='staffadmin',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.program'),
        ),
        migrations.AlterField(
            model_name='staffadmin',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.year'),
        ),
    ]
