# Generated by Django 3.2.13 on 2022-07-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20220712_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.CharField(choices=[('1', 'Student'), ('2', 'Staff')], max_length=10, null=True),
        ),
    ]
