# Generated by Django 3.2.13 on 2022-07-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_user_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='staff',
            new_name='role',
        ),
    ]
