# Generated by Django 3.2.13 on 2022-07-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_staff_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='status',
        ),
    ]
