# Generated by Django 3.2.13 on 2022-07-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_events_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
