# Generated by Django 3.2.13 on 2022-07-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_events_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
