# Generated by Django 3.2.13 on 2022-07-20 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_notice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.college'),
        ),
    ]
