# Generated by Django 3.2.13 on 2022-07-22 20:02

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_events_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_img1',
            field=models.ImageField(blank=True, upload_to=base.models.upload_path),
        ),
        migrations.AddField(
            model_name='events',
            name='event_img2',
            field=models.ImageField(blank=True, upload_to=base.models.upload_path),
        ),
        migrations.AddField(
            model_name='events',
            name='event_img3',
            field=models.ImageField(blank=True, upload_to=base.models.upload_path),
        ),
        migrations.AddField(
            model_name='events',
            name='event_img4',
            field=models.ImageField(blank=True, upload_to=base.models.upload_path),
        ),
    ]
