# Generated by Django 3.2.13 on 2022-07-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_notice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_date',
            field=models.DateField(),
        ),
    ]
