# Generated by Django 3.2.13 on 2022-07-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_notice_notice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_desc',
            field=models.CharField(max_length=1100),
        ),
    ]
