# Generated by Django 3.2.13 on 2022-07-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_notice_notice_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_desc',
            field=models.CharField(max_length=5000),
        ),
    ]
