# Generated by Django 3.2.13 on 2022-07-23 12:01

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_notice_notice_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notice_file',
            field=models.FileField(blank=True, upload_to=base.models.upload_path_notice_files),
        ),
    ]
