# Generated by Django 3.2.13 on 2022-07-29 11:52

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_notice_notice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='notes_file',
            field=models.FileField(blank=True, upload_to=base.models.upload_path_notes_files),
        ),
    ]
