# Generated by Django 3.2.13 on 2022-08-10 05:46

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_notes_notes_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_img1',
            field=models.ImageField(blank=True, default=True, upload_to=base.models.upload_path),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_img2',
            field=models.ImageField(blank=True, default=True, upload_to=base.models.upload_path),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_img3',
            field=models.ImageField(blank=True, default=True, upload_to=base.models.upload_path),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_img4',
            field=models.ImageField(blank=True, default=True, upload_to=base.models.upload_path),
        ),
    ]
