# Generated by Django 3.2.13 on 2022-08-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_notes_notes_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='notes_unit_no',
            field=models.IntegerField(default=True),
        ),
    ]
