# Generated by Django 3.2.13 on 2022-08-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_notes_notes_unit_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notes_unit',
            field=models.CharField(max_length=260),
        ),
    ]
