# Generated by Django 3.2.13 on 2022-08-12 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notes_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.subject'),
        ),
    ]
