# Generated by Django 3.2.13 on 2022-08-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_notes_notes_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='program',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='year',
        ),
    ]
